apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    apps: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend 
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: reeceqa/python-backend
        ports:    
        - containerPort: 5001
        
