apiVersion: apps/v1
kind: Deployment
metadata: 
  name: task1-deployment
  labels: 
    apps: task1-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: task1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata: 
      labels:
        app: task1
    spec: 
      containers:
      - name: task1
        image: chrisreeves1/myapp
        ports:
        - containerPort: 5500
