apiVersion: apps/v1
kind: Deployment
metadata: 
  name: task2app-deployment
  labels:
    apps: task2app-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:  
      app: mytriotaskflaskapp
  strategy: 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata: 
      labels:
        app: mytriotaskflaskapp
    spec:
      containers:
      - name: mytriotaskflaskapp
        image: chrisreeves1/mytriotaskflaskapp:2.0
        ports:
        - containerPort: 5000
---
apiVersion: v1 
kind: Service
metadata:
  name: mytriotaskflaskapp
spec: 
  type: LoadBalancer
  selector:
    app: mytriotaskflaskapp
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
